#!/bin/bash

# Print the X-Forwarded for headers (Capital X and F) from headers.txt
# the sed command below greps the headers.txt file and Capitalizes all x's and f's  
# headers | sed 's/x/X/g;s/f/F/g;' | rg '^X-F'
echo ""
printf "\e[1;31m X-Forwarded-For \e[0m\n"
echo   " X-Forwarded-host~%s.%h"
printf "\e[1;31m X-Forwarded-proto \e[0m\n"
printf "\e[1;31m X-Forwarded-port \e[0m\n"
printf "\e[1;31m X-Forwarded-preFiX \e[0m\n"
printf "\e[1;31m X-Forwarded-protocol \e[0m\n"
printf "\e[1;31m X-Forwarded-ssl \e[0m\n"
echo   " X-Forwarded-server~%s.%h"
printf "\e[1;31m X-Fb-user-remote-addr \e[0m\n"
printf "\e[1;31m X-File-id \e[0m\n"
printf "\e[1;31m X-File-resume \e[0m\n"
printf "\e[1;31m X-Foo-bar \e[0m\n"
printf "\e[1;31m X-Forwarded-For-original \e[0m\n"
printf "\e[1;31m X-Forwarder-For \e[0m\n"
printf "\e[1;31m X-Forward-proto \e[0m\n"
printf "\e[1;31m X-From \e[0m\n"
printf "\e[1;31m X-Filename \e[0m\n"
printf "\e[1;31m X-Flash-version \e[0m\n"
printf "\e[1;31m X-FlX-consumer-key \e[0m\n"
printf "\e[1;31m X-FlX-consumer-secret \e[0m\n"
printf "\e[1;31m X-FlX-redirect-url \e[0m\n"
printf "\e[1;31m X-Forwarded-scheme \e[0m\n"
printf "\e[1;31m X-Foo \e[0m\n"
printf "\e[1;31m X-Forwarded-by \e[0m\n"
printf "\e[1;31m X-Fireloggerauth \e[0m\n"
printf "\e[1;31m X-Forward-For \e[0m\n"
printf "\e[1;31m X-File-type \e[0m\n"
printf "\e[1;31m X-Forwarded-ssl \e[0m\n"
printf "\e[1;31m X-File-size \e[0m\n"
printf "\e[1;31m X-Firelogger \e[0m\n"
printf "\e[1;31m X-File-name \e[0m\n"
printf "\e[1;31m X-Firephp-version \e[0m\n"
printf "\e[1;31m X-Forwarded \e[0m\n"
printf "\e[1;31m X-Forwarded-server \e[0m\n"
printf "\e[1;31m X-Forwarded-host \e[0m\n"
echo ""
